uncomment cloud defense

diff --git a/buildspec-staging.yml b/buildspec-staging.yml
--- a/buildspec-staging.yml
+++ b/buildspec-staging.yml
@@ -18,25 +18,25 @@ phases:
       - IMAGE_TAG=staging_${COMMIT_HASH:=latest}
       - GITHUB_BRANCH_NAME="${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/}"
       - GITHUB_REPO_URL="https://${GITHUB_PERSONAL_ACCESS_TOKEN}@${CODEBUILD_SOURCE_REPO_URL#https://}"
-      # - echo Install cloud defense cli
-      # - curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz
-      # - sudo tar -C /usr/local/bin -xzf /tmp/cd-latest-linux-x64.tar.gz
-      # - chmod +x /usr/local/bin/cdefense
+      - echo Install cloud defense cli
+      - curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz
+      - sudo tar -C /usr/local/bin -xzf /tmp/cd-latest-linux-x64.tar.gz
+      - chmod +x /usr/local/bin/cdefense
       - echo end of pre_build phase
   build:
     commands:
       - echo Build started on `date`
-      # - echo Start cloud defense vulnerability scan on codebase
-      # - |
-      #   set +e  # Disable immediate exit on error
-      #   cdefense online --api-key=$CLOUD_DEFENSE_API --tag=$COMMIT_HASH --repository-url=$GITHUB_REPO_URL --branch-name=$GITHUB_BRANCH_NAME
-      #   exit_code=$?
-      #   set -e  # Re-enable immediate exit on error
-      #   if [ $exit_code -eq 1 ]; then
-      #    echo "Ignore exit code 1"
-      #   else
-      #    exit $exit_code
-      #   fi
+      - echo Start cloud defense vulnerability scan on codebase
+      - |
+        set +e  # Disable immediate exit on error
+        cdefense online --api-key=$CLOUD_DEFENSE_API --tag=$COMMIT_HASH --repository-url=$GITHUB_REPO_URL --branch-name=$GITHUB_BRANCH_NAME
+        exit_code=$?
+        set -e  # Re-enable immediate exit on error
+        if [ $exit_code -eq 1 ]; then
+         echo "Ignore exit code 1"
+        else
+         exit $exit_code
+        fi
       - echo Building the Docker image...
       - docker build -t $REPOSITORY_URI:latest .
       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
